version: '3.9'

services:
  db:
    image: postgres:14.18
    container_name: postgres-server
    hostname: pg-db
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data:cached
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      retries: 5
      start_period: 5s
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9090:8080